/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sonar.send;

import java.io.*;
import sonar.minimodem.*;
import sonar.socket.*;

public class SendMain {
  public static void main(String[] args) {
    try {
      MinimodemReceiver rx = new MinimodemReceiver(BaudMode.BELL202);
      MinimodemTransmitter tx = new MinimodemTransmitter(BaudMode.BELL202);

      BufferedTransmitter transmitter = new BufferedTransmitter(tx);
      BufferedReceiver receiver = new BufferedReceiver(rx);

      SonarSocket socket = new SonarSocket(receiver, transmitter);

      System.out.println("Leyendo archivo '" + args[0] + "'");
      File file = new File(args[0]);

      FileInputStream fis = new FileInputStream(file);

      if (!file.exists()) {
        System.err.printf("El archivo '%s' no existe.", args[0]);
      }

      Packet syncPacket = new Packet(666, 999);

      socket.writePacket(syncPacket);

      // Bloquea hasta que el servidor recibe el paquete y lo vuelve a enviar
      Packet received = socket.receivePacket();

      System.out.println("Recibí paquete de confirmación");

    } catch (Exception e) {
      System.err.println("El programa falló por los siguientes motivos:");
      System.err.println(e.toString());
    }
  }
}
